---
- hosts: Jenkins-Master
  become: true
  tasks:
    - name: Update apt cache and repositories
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Add Jenkins Repository Key (Securely)
      get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add Jenkins Repository
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        state: present
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins Service
      service:
        name: jenkins
        state: started
    - name: Enable Jenkins Service
      service:
        name: jenkins
        enabled: yes
      